### ISSUE TITLE
Upgrade to Cake 2.0

### ISSUE THREAD

**Issue by paulmilbank** [cake-contrib/Cake.Yarn#44]
https://github.com/cake-contrib/cake-yarn/pull/42

Can this be upgraded to Cake 2.0? All tests pass locally, but obviously it would lose support for running on dotnet 4.8 and below only build agents. I tried it with multi targeting for dotnet core 3.1 and net6.0 and it works fine, so I can add that to the PR if needed. Now net5.0 is out of support, it doesn't seem worth targeting that framework too.

**Comment by paulmilbank** [comment]
Forgot to say, I added net5.0 as a target as Cake still supports it currently.

**Comment by augustoproiete** [comment]
:tada: The changes implemented in response to this issue shipped with **Cake.Yarn v1.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/cake-contrib/Cake.Yarn/releases/tag/1.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Cake.Yarn/1.0.0)
